'use strict';
const $=id=>document.getElementById(id),C=EFSCore,STORAGE='efs_grading_v2';
let state={versions:{},results:[]},draft=null,busy=false,urls=[],epoch=0;
try{const s=JSON.parse(localStorage.getItem(STORAGE));if(s&&s.versions&&Array.isArray(s.results))state=s;}catch{}
function message(text,error=false){$('status').textContent=text;$('status').className=error?'error':'notice';}
function store(next){try{localStorage.setItem(STORAGE,JSON.stringify(next));state=next;}catch{throw Error('Không lưu được trên thiết bị. Hãy kiểm tra dung lượng / quyền lưu của trình duyệt.');}}
function go(n){for(let i=1;i<=3;i++)$('step'+i).hidden=i!==Number(n);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.step===String(n)));}
function element(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
function clearDraft(){draft=null;$('approved').checked=false;$('reviewTable').replaceChildren();$('score').textContent='';$('reviewName').textContent='Đọc bài làm ở bước 2 để tạo kết quả.';}
function invalidate(){epoch++;$('checked').checked=false;clearDraft();}
function rows(){return [...$('keyRows').children].map(tr=>({number:tr.querySelector('.qnumber').value,type:tr.querySelector('.qtype').value,key:tr.querySelector('.qkey').value,points:tr.querySelector('.qpoints').value}));}
function keyTotal(){$('keyTotal').textContent='Tổng điểm: '+rows().reduce((a,r)=>a+(Number(r.points)||0),0).toFixed(2);}
function addRow(q={number:Math.max(0,...rows().map(r=>Number(r.number)))+1,type:'mc',key:'',points:1}){const tr=element('tr');for(const field of ['number','type','key','points']){const td=element('td'),input=element(field==='type'?'select':field==='key'?'textarea':'input');input.className='q'+field;input.setAttribute('aria-label',field+' câu '+q.number);if(field==='type'){for(const [v,t] of [['mc','Trắc nghiệm'],['short','Câu ngắn'],['written','Tự luận']]){const o=element('option',t);o.value=v;input.append(o);}}else if(field!=='key'){input.type='number';input.min=field==='number'?'1':'0.01';input.max=field==='number'?'200':'100';input.step=field==='number'?'1':'0.01';}input.value=q[field];input.oninput=keyTotal;td.append(input);tr.append(td);}const td=element('td'),del=element('button','×');del.setAttribute('aria-label','Xóa câu '+q.number);del.onclick=()=>{tr.remove();keyTotal();};td.append(del);tr.append(td);$('keyRows').append(tr);keyTotal();}
function refresh(){for(const id of ['version','editVersion']){const selected=$(id).value;$(id).replaceChildren();if(id==='editVersion'){const o=element('option','Mã đề mới');o.value='';$(id).append(o);}for(const code of Object.keys(state.versions)){const o=element('option',code+' · '+state.versions[code].title);o.value=code;$(id).append(o);}if(state.versions[selected])$(id).value=selected;}$('summary').textContent=Object.keys(state.versions).length+' mã đề · '+state.results.length+' bài đã duyệt';$('results').replaceChildren();for(const r of state.results){const tr=element('tr');for(const v of [r.student,r.code,r.title,r.score.toFixed(2)+' / '+r.max])tr.append(element('td',v));$('results').append(tr);}if(!state.results.length){const td=element('td','Chưa có bài đã duyệt.');td.colSpan=4;const tr=element('tr');tr.append(td);$('results').append(tr);}}
const scripts={};
let pdfReader;
async function loadPdf(){if(!pdfReader)pdfReader=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.2.67/build/pdf.mjs');return pdfReader;}
function loadScript(url){if(scripts[url])return scripts[url];scripts[url]=new Promise((resolve,reject)=>{const s=element('script');s.src=url;s.onload=resolve;s.onerror=()=>{s.remove();delete scripts[url];reject(Error('Không tải được bộ đọc. Kiểm tra mạng rồi thử lại.'));};document.head.append(s);});return scripts[url];}
async function ocr(image){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js');const worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')message('Đang đọc ảnh: '+Math.round(m.progress*100)+'%');}});try{const {data}=await worker.recognize(image);return {text:data.text,warnings:data.confidence<80?['OCR chưa chắc chắn ('+Math.round(data.confidence)+'%). Hãy kiểm tra mọi câu.']:[]};}finally{await worker.terminate();}}
async function readFile(file){if(!file)throw Error('Chọn file trước khi đọc.');if(file.size>20*1024*1024)throw Error('Mỗi file tối đa 20 MB.');const ext=file.name.split('.').pop().toLowerCase();if(ext==='txt')return {text:await file.text(),warnings:[]};if(ext==='docx'){await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js');const result=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return {text:result.value,warnings:result.messages.length?['File Word có cảnh báo khi trích xuất. Kiểm tra nội dung đã đọc.']:[]};}if(ext==='pdf'){const pdfjsLib=await loadPdf();pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.2.67/build/pdf.worker.mjs';const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;try{if(doc.numPages>20)throw Error('PDF tối đa 20 trang.');const texts=[],warnings=[];for(let i=1;i<=doc.numPages;i++){message('Đọc PDF: trang '+i+'/'+doc.numPages);const page=await doc.getPage(i),content=await page.getTextContent();let text='',lastY=null;for(const item of content.items){const y=item.transform?.[5];if(lastY!==null&&Math.abs(y-lastY)>3)text+='\n';text+=item.str+' ';if(item.hasEOL)text+='\n';lastY=y;}if(text.trim().length<10){const viewport=page.getViewport({scale:1.8});if(viewport.width*viewport.height>16000000)throw Error('Trang PDF quá lớn. Hãy giảm kích thước trước khi đọc.');const canvas=element('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const result=await ocr(canvas);text=result.text;warnings.push(...result.warnings);}texts.push(text);}return {text:texts.join('\n'),warnings};}finally{await doc.destroy();}}if(['png','jpg','jpeg','webp'].includes(ext)||file.type.startsWith('image/'))return ocr(file);throw Error('Hỗ trợ DOCX, PDF, TXT, PNG, JPG và WebP. File .doc cũ cần chuyển thành .docx.');}
async function operation(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message||'Không đọc được file. Hãy kiểm tra định dạng.',true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function preview(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];$('previews').replaceChildren();for(const f of [...$('files').files,...$('camera').files]){if(f.type.startsWith('image/')){const img=element('img');img.alt=f.name;img.src=URL.createObjectURL(f);urls.push(img.src);$('previews').append(img);}else $('previews').append(element('p',f.name));}}
function getReview(){if(!draft)throw Error('Chưa có bài làm để duyệt.');const answers={},manual={};for(const tr of $('reviewTable').querySelectorAll('tbody tr')){const n=Number(tr.dataset.number);answers[n]=tr.querySelector('.answer').value;const s=tr.querySelector('.manual');if(s)manual[n]=s.value;}return C.grade(draft.questions,answers,manual);}
function updateScore(){try{const g=getReview();$('score').textContent=(g.complete?'Điểm: ':'Điểm tạm: ')+g.score.toFixed(2)+' / '+g.max.toFixed(2)+(g.complete?'':' · Còn tự luận chưa chấm');$('reviewTable').querySelectorAll('tbody tr').forEach((tr,i)=>{tr.querySelector('.earned').textContent=g.items[i].earned===null?'Chờ chấm':g.items[i].earned.toFixed(2);});}catch(e){$('score').textContent=e.message;}}
function renderReview(){const table=element('table'),head=element('thead'),hr=element('tr');for(const s of ['Câu','Câu trả lời đã đọc','Đáp án / barem','Điểm / tối đa'])hr.append(element('th',s));head.append(hr);table.append(head);const body=element('tbody');for(const q of draft.questions){const tr=element('tr');tr.dataset.number=q.number;tr.append(element('td',q.number));const a=element('td'),input=element('textarea');input.className='answer';input.value=draft.answers[q.number]||'';input.setAttribute('aria-label','Câu trả lời câu '+q.number);input.oninput=()=>{$('approved').checked=false;updateScore();};a.append(input);tr.append(a,element('td',q.key));const td=element('td');if(q.type==='written'){const score=element('input');score.type='number';score.className='manual';score.min=0;score.max=q.points;score.step='0.01';score.placeholder='Điểm';score.setAttribute('aria-label','Điểm tự luận câu '+q.number);score.oninput=()=>{$('approved').checked=false;updateScore();};td.append(score);}td.append(element('span',' / '+q.points+' · '));const earned=element('span');earned.className='earned';td.append(earned);tr.append(td);body.append(tr);}table.append(body);$('reviewTable').replaceChildren(table);$('reviewName').textContent=draft.student+' · Mã '+draft.code+' · '+draft.title;updateScore();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.step));
$('addQuestion').onclick=()=>addRow();
$('buildKey').onclick=()=>{try{const parsed=C.parseAnswers($('keyText').value);if(parsed.conflicts.length)throw Error('Đáp án trùng khác nhau tại câu '+parsed.conflicts.join(', '));const entries=Object.entries(parsed.answers);if(!entries.length)throw Error('Không tìm thấy đáp án có số câu. Dùng mỗi dòng một câu: 1 A.');if(rows().length&&!confirm('Thay bảng đáp án đang nhập bằng nội dung này?'))return;$('keyRows').replaceChildren();for(const [number,key] of entries)addRow({number,type:/^[A-D]$/i.test(key)?'mc':'short',key,points:Number((10/entries.length).toFixed(4))});message('Đã nhận '+entries.length+' câu. Kiểm tra loại câu, đáp án và điểm trước khi lưu.');}catch(e){message(e.message,true);}};
$('saveKey').onclick=()=>{try{const code=$('code').value.trim(),title=$('title').value.trim();if(!code||!title)throw Error('Nhập tên bài kiểm tra và mã đề.');const questions=C.validateKey(rows());if(state.versions[code]&&!confirm('Cập nhật mã '+code+'? Các điểm đã lưu giữ nguyên đáp án và thang điểm cũ.'))return;store({...state,versions:{...state.versions,[code]:{title,questions}}});invalidate();refresh();$('version').value=code;message('Đã lưu mã '+code+'. Có thể đọc bài làm.');go(2);}catch(e){message(e.message,true);}};
$('editVersion').onchange=()=>{const v=state.versions[$('editVersion').value];if(!v)return;$('code').value=$('editVersion').value;$('title').value=v.title;$('keyRows').replaceChildren();v.questions.forEach(addRow);};
$('readKey').onclick=()=>operation(async()=>{message('Đang đọc đáp án…');const r=await readFile($('keyFile').files[0]);if(!r.text.trim())throw Error('Không đọc được chữ từ file đáp án.');$('keyText').value=r.text;message('Đã đọc đáp án. '+r.warnings.join(' ')+' Kiểm tra văn bản rồi đưa vào bảng đáp án.');});
$('readSubmission').onclick=()=>operation(async()=>{invalidate();const token=epoch;const files=[...$('files').files,...$('camera').files];if(!files.length)throw Error('Chọn bài làm hoặc chụp ảnh trước.');if(files.length>20||files.reduce((n,f)=>n+f.size,0)>60*1024*1024)throw Error('Tối đa 20 file, tổng dung lượng 60 MB.');const texts=[],warnings=[];for(const f of files){message('Đang đọc '+f.name);const r=await readFile(f);texts.push(r.text);warnings.push(...r.warnings);}if(token!==epoch)throw Error('Bài làm đã thay đổi khi đang đọc. Vui lòng đọc lại.');if(!texts.join('').trim())throw Error('Không nhận diện được chữ. Hãy chụp rõ hơn.');$('recognized').value=texts.join('\n');message('Đã đọc '+files.length+' file. '+warnings.join(' ')+' Đối chiếu nội dung trước khi chấm.');});
for(const id of ['files','camera'])$(id).onchange=()=>{invalidate();$('recognized').value='';preview();};
$('recognized').oninput=invalidate;for(const id of ['student','version'])$(id).onchange=invalidate;
$('toReview').onclick=()=>{try{if(busy)throw Error('Đợi đọc file hoàn tất.');const student=$('student').value.trim(),code=$('version').value,v=state.versions[code];if(!v)throw Error('Lưu đáp án ở bước 1 trước.');if(!student)throw Error('Nhập mã học sinh.');if(!$('recognized').value.trim())throw Error('Chưa có nội dung bài làm.');if(!$('checked').checked)throw Error('Đối chiếu nội dung nhận diện và đánh dấu xác nhận trước.');const parsed=C.parseAnswers($('recognized').value);if(parsed.conflicts.length)throw Error('Có nhiều câu trả lời khác nhau cùng số câu: '+parsed.conflicts.join(', ')+'. Sửa nội dung nhận diện trước.');if(!Object.keys(parsed.answers).length)throw Error('Chưa tìm thấy câu trả lời có số câu. Kiểm tra định dạng nội dung nhận diện.');const extra=Object.keys(parsed.answers).filter(n=>!v.questions.some(q=>q.number===Number(n)));const missing=v.questions.filter(q=>!parsed.answers[q.number]);draft={student,code,title:v.title,questions:structuredClone(v.questions),answers:parsed.answers};$('approved').checked=false;renderReview();go(3);message((missing.length?'Chưa đọc được câu '+missing.map(q=>q.number).join(', ')+'. Câu chưa có câu trả lời được tính 0; kiểm tra bài gốc. ':'')+(extra.length?'Số câu ngoài đáp án: '+extra.join(', ')+'. ':'')+'Duyệt từng câu trước khi lưu.');}catch(e){message(e.message,true);}};
$('saveResult').onclick=()=>{try{if(!draft)throw Error('Chưa có bài làm để duyệt.');if(!$('approved').checked)throw Error('Xác nhận đã duyệt điểm từng câu.');const result=getReview();if(!result.complete)throw Error('Chấm đủ các câu tự luận trước khi lưu.');const duplicate=state.results.some(r=>r.student===draft.student&&r.code===draft.code&&r.title===draft.title);if(duplicate&&!confirm('Đã có điểm của học sinh này. Thay kết quả cũ?'))return;const record={...draft,...result,savedAt:new Date().toISOString()};store({...state,results:[...state.results.filter(r=>!(r.student===draft.student&&r.code===draft.code&&r.title===draft.title)),record]});refresh();clearDraft();message('Đã lưu điểm. Xuất CSV hoặc chấm bài tiếp theo.');}catch(e){message(e.message,true);}};
$('nextStudent').onclick=()=>{invalidate();$('student').value='';$('recognized').value='';$('files').value='';$('camera').value='';preview();go(2);$('student').focus();};
$('export').onclick=()=>{if(!state.results.length){message('Chưa có điểm để xuất.',true);return;}const values=[['Mã HS','Mã đề','Bài kiểm tra','Điểm','Tối đa','Ngày duyệt','Chi tiết'],...state.results.map(r=>[r.student,r.code,r.title,r.score,r.max,r.savedAt,r.items.map(q=>'Câu '+q.number+': '+q.answer+'; '+q.earned+'/'+q.points).join(' | ')])];const blob=new Blob(['\ufeff'+values.map(r=>r.map(C.csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download='EFS_Grading.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
refresh();if(Object.keys(state.versions).length){$('editVersion').value=Object.keys(state.versions)[0];$('editVersion').onchange();}
