'use strict';
// Only explicit identity and exam headers join pages. No ordering/answer-pattern inference.
function originalDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('efs_grading_originals',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Không mở được kho bài gốc.'));});}
async function keepOriginal(id,file){const db=await originalDB();try{await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(Error('Không lưu được bài gốc; kiểm tra dung lượng.'));tx.onabort=()=>reject(Error('Lưu bài gốc bị hủy.'));});}finally{db.close();}}
async function showOriginal(id,queueId){const db=await originalDB();try{const file=await new Promise((resolve,reject)=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=reject;});if(queueId!==activeQueueId)return;if(!file)throw Error('Bài gốc không còn trên thiết bị; chọn lại file để đối chiếu.');const raster=['image/png','image/jpeg','image/webp'].includes(file.type),safeBlob=new Blob([file],{type:raster?file.type:'application/octet-stream'}),url=URL.createObjectURL(safeBlob);urls.push(url);const link=element('a','Tải bài gốc '+(file.name||''));link.href=url;link.download=file.name||'bai-goc';$('previews').append(link);if(raster){const img=element('img');img.alt=file.name||'Bài gốc';img.src=url;$('previews').append(img);}}finally{db.close();}}
function renderQueue(){if(!$('queue'))return;$('queue').replaceChildren();for(const item of state.queue||[]){const row=element('div');row.className='saved-version';const info=element('div');info.append(element('strong',(item.student||'Chưa rõ HS')+' · '+(item.code||'Chưa rõ mã đề')+' · '+item.status),element('p',item.pages.map(p=>p.name+' / trang '+p.number).join(' · ')),element('p',item.issues.join('; ')));if(item.candidate)info.append(element('p','✓ Giáo viên đã kiểm tra từng câu; chờ duyệt loạt'));const button=element('button',item.status==='APPROVED'?'Xem kết quả đã khóa':'Kiểm tra bài');button.className='secondary';button.onclick=()=>{if(item.status==='APPROVED'){message('Bài đã duyệt và khóa. Bản điểm giữ nguyên; muốn chấm lại hãy tạo lần đọc mới.');return;}if(item.candidate){store({...state,queue:state.queue.map(x=>x.id===item.id?{...x,candidate:null}:x)});renderQueue();}activeQueueId=item.id;invalidate();$('student').value=item.student;$('recognized').value=item.text;preview();for(const page of item.pages)if(page.originalId)showOriginal(page.originalId,item.id).catch(e=>{if(typeof document!=='undefined'&&document.getElementById('status')&&activeQueueId===item.id)message(e.message,true);});detectSubmissionCode();go(2);message('Đối chiếu bài gốc, sửa mã HS / mã đề / nội dung khi cần rồi chuyển duyệt điểm.');};row.append(info,button);$('queue').append(row);}}
$('readBatch').onclick=()=>operation(async()=>{if(!$('batchMode').checked)throw Error('Chọn chế độ nhiều học sinh trước.');if(!Object.keys(state.versions).length)throw Error('Lưu mã đề trước.');const files=[...$('files').files,...$('camera').files];if(!files.length||files.length>20||files.reduce((n,f)=>n+f.size,0)>60*1024*1024)throw Error('Chọn 1–20 file, tổng tối đa 60 MB.');if((state.queue||[]).length+files.length*20>1000)throw Error('Hàng đợi tối đa 1.000 bài; sao lưu và xử lý trước.');activeQueueId=null;invalidate();const batchId=crypto.randomUUID();for(let i=0;i<files.length;i++){const file=files[i],originalId=crypto.randomUUID();const pending={id:originalId,batchId,student:'',code:'',text:'',pages:[{name:file.name,number:1,originalId}],issues:[],status:'PROCESSING'};store({...state,queue:[...(state.queue||[]),pending]});renderQueue();$('batchProgress').textContent='Đang đọc '+(i+1)+'/'+files.length+' — '+file.name;let pages;try{if(file.size>20*1024*1024)throw Error('Mỗi file tối đa 20 MB.');await keepOriginal(originalId,file);const result=await readFile(file);pages=(result.pages||[{text:result.text,warnings:result.warnings,confidence:result.confidence}]).map((p,n)=>({...p,name:file.name,number:n+1,originalId}));}catch(e){pages=[{name:file.name,number:1,originalId,text:'',error:e.message}];}const incoming=EFSWorkflow.groupPages(pages,state.versions,()=>crypto.randomUUID()).map(x=>({...x,batchId}));const queue=(state.queue||[]).filter(x=>x.id!==originalId);for(const item of incoming){const previous=queue.find(x=>x.batchId===batchId&&x.student&&x.student===item.student&&x.code&&x.code===item.code&&x.status!=='FAILED');if(previous&&item.status!=='FAILED'){previous.text+='\n'+item.text;previous.pages.push(...item.pages);previous.issues.push(...item.issues);const conflicts=C.parseAnswers(previous.text).conflicts;if(conflicts.length)previous.issues.push('Câu trả lời mâu thuẫn: '+conflicts.join(', '));previous.issues=[...new Set(previous.issues)];}else queue.push(item);}store({...state,queue});renderQueue();}$('batchProgress').textContent='Đã xử lý '+files.length+' file. Bài lỗi được giữ riêng; kiểm tra từng bài trước khi duyệt.';message('Hàng đợi đã lưu trên thiết bị. Không tự nối trang thiếu mã HS / mã đề.');});
$('stageBatch').onclick=()=>{try{if(!activeQueueId||!draft)throw Error('Mở bài trong hàng đợi trước.');if(!$('approved').checked)throw Error('Xác nhận đã duyệt từng câu.');const grade=getReview();if(!grade.complete)throw Error('Còn câu chưa chấm.');const item=state.queue.find(x=>x.id===activeQueueId);if(!item||item.status==='APPROVED')throw Error('Bài đã khóa hoặc không còn trong hàng đợi.');const candidate={...draft,...grade,status:'APPROVED',submissionId:item.id,id:crypto.randomUUID(),savedAt:new Date().toISOString()};store({...state,queue:state.queue.map(x=>x.id===item.id?{...x,student:draft.student,code:draft.code,text:$('recognized').value,keySnapshot:{title:draft.title,questions:draft.questions,revision:draft.keyRevision},issues:[],status:'NEEDS REVIEW',candidate}:x)});activeQueueId=null;clearDraft();renderQueue();go(2);message('Đã giữ bản điểm giáo viên kiểm tra để duyệt loạt.');}catch(e){message(e.message,true);}};
$('approveBatch').onclick=()=>{try{const eligible=(state.queue||[]).filter(x=>x.status==='NEEDS REVIEW'&&x.candidate&&x.issues.length===0&&x.candidate.complete);if(!eligible.length)throw Error('Chưa có bài đã kiểm tra đủ điều kiện.');if(!confirm('Duyệt và khóa '+eligible.length+' bài đã kiểm tra từng câu? Bài lỗi / chưa kiểm tra tiếp tục chờ.'))return;const ids=new Set(eligible.map(x=>x.id));store({...state,results:[...state.results,...eligible.map(x=>x.candidate)],queue:state.queue.map(x=>ids.has(x.id)?{...x,status:'APPROVED',resultId:x.candidate.id}:x),audit:[...(state.audit||[]),...eligible.map(x=>({event:'APPROVED_BATCH',resultId:x.candidate.id,at:new Date().toISOString()}))]});refresh();renderQueue();message('Đã duyệt '+eligible.length+' bài đủ điều kiện.');}catch(e){message(e.message,true);}};
if((state.queue||[]).some(x=>x.status==='PROCESSING')){store({...state,queue:state.queue.map(x=>x.status==='PROCESSING'?{...x,status:'FAILED',issues:[...x.issues,'Lần đọc bị gián đoạn. Chọn lại file để thử lại.']}:x)});}
renderQueue();

const readSingleSubmission=$('readSubmission').onclick;
$('readSubmission').onclick=()=> $('batchMode').checked?$('readBatch').onclick():readSingleSubmission();
