(function(root){'use strict';
function normalize(s){return String(s??'').normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();}
function parseAnswers(text){const answers={},conflicts=[];const headers=/^[ \t]*(?:mã[ \t]*(?:số[ \t]*)?đề(?:[ \t]*thi)?|ma[ \t]*(?:so[ \t]*)?de(?:[ \t]*thi)?|(?:exam|test|paper|version)[ \t]*code|mã[ \t]*(?:học[ \t]*sinh|hs)|ma[ \t]*(?:hoc[ \t]*sinh|hs)|student[ \t]*id)[ \t]*[:#=–-]?.*$/gim;
const source=String(text).normalize('NFKC').replace(headers,'');
const re=/(?:^|[\n\r\t ;,])(?:câu[ \t]*|question[ \t]*)?(\d{1,3})[ \t]*[).:\-]?[ \t]*([^\n\r;]+?)(?=(?:[ \t]+(?:câu[ \t]*|question[ \t]*)?\d{1,3}[ \t]*[).:\-]?[ \t]*[A-D]\b)|[\n\r;]|$)/gi;const entries=[];let current=null;for(const line of source.split(/\r?\n|\r/)){if(/^[ \t]*(?:câu[ \t]*|question[ \t]*)?\d{1,3}[ \t]*[).:\-]?[ \t]*\S/i.test(line)){re.lastIndex=0;let m;while((m=re.exec(line))){const n=Number(m[1]),v=m[2].trim();if(!n||!v)continue;current={n,v};entries.push(current);}}else if(current&&line.trim())current.v+='\n'+line.trim();}for(const {n,v} of entries){if(Object.hasOwn(answers,n)&&normalize(answers[n])!==normalize(v))conflicts.push(n);answers[n]=v;}return {answers,conflicts:[...new Set(conflicts)]};}
function detectExamCode(text,codes){
 const canonical=s=>String(s).normalize('NFKC').trim().toUpperCase();
 const source=String(text).normalize('NFKC').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D');
 const re=/\b(?:ma[ \t]*(?:so[ \t]*)?de(?:[ \t]*thi)?|exam[ \t]*code|test[ \t]*code|paper[ \t]*code|version[ \t]*code)[ \t]*(?:[:#=–-][ \t]*)?[([{]?[ \t]*([a-z0-9][^\s\])},;:]*)/gi;
 const found=[];let m;while((m=re.exec(source)))found.push(canonical(m[1]));
 const observed=[...new Set(found)];
 if(observed.length>1)return {status:'conflict',observed,code:null};
 if(observed.length===1){const matches=codes.filter(c=>canonical(c)===observed[0]);if(matches.length===1)return {status:'matched',observed,code:matches[0]};return {status:matches.length?'conflict':'unknown',observed,code:null};}
 if(codes.length===1)return {status:'single',observed,code:codes[0]};
 return {status:'missing',observed,code:null};
}
function validateKey(rows){if(!rows.length)throw Error('Cần ít nhất một câu có đáp án.');const seen=new Set();return rows.map(r=>{const n=Number(r.number),points=Number(r.points),type=r.type;if(!Number.isInteger(n)||n<1||n>200||seen.has(n))throw Error('Số câu phải từ 1–200 và không trùng.');seen.add(n);if(!['mc','short','written'].includes(type)||!Number.isFinite(points)||points<=0||points>100)throw Error('Kiểm tra loại câu và điểm từng câu.');const key=String(r.key||'').trim();if(!key)throw Error('Câu '+n+' chưa có đáp án hoặc barem.');if(type==='short'&&key.split('|').some(k=>!k.trim()))throw Error('Câu '+n+' có đáp án tương đương trống.');if(type==='mc'&&!/^[A-D]$/i.test(key))throw Error('Câu '+n+' cần một đáp án A, B, C hoặc D.');const result={number:n,type,points,key};
if(r.policy){const p=r.policy;if(typeof p!=='object'||Array.isArray(p))throw Error('Quy tắc chấm không hợp lệ.');for(const k of ['caseSensitive','ignorePunctuation','reviewUnmatched'])if(k in p&&typeof p[k]!=='boolean')throw Error('Quy tắc '+k+' phải là đúng/sai.');const partial=p.partial||[];if(!Array.isArray(partial)||partial.length>100)throw Error('Tối đa 100 đáp án cho điểm một phần.');result.policy={caseSensitive:!!p.caseSensitive,ignorePunctuation:!!p.ignorePunctuation,reviewUnmatched:!!p.reviewUnmatched,partial:partial.map(x=>{if(typeof x.answer!=='string'||!x.answer.trim()||!Number.isFinite(x.points)||x.points<0||x.points>=points)throw Error('Điểm một phần không hợp lệ.');return {answer:x.answer.trim(),points:x.points};})};}
if(r.rubric){if(!Array.isArray(r.rubric)||!r.rubric.length||r.rubric.length>20)throw Error('Barem cần 1–20 tiêu chí.');const ids=new Set();result.rubric=r.rubric.map(x=>{if(!x||typeof x.id!=='string'||!x.id.trim()||ids.has(x.id)||typeof x.description!=='string'||!x.description.trim()||!Number.isFinite(x.points)||x.points<=0)throw Error('Tiêu chí barem không hợp lệ.');ids.add(x.id);return {id:x.id,description:x.description,points:x.points};});if(Math.abs(result.rubric.reduce((n,x)=>n+x.points,0)-points)>0.001)throw Error('Tổng điểm tiêu chí phải bằng điểm câu.');}
if(result.policy){if(key.split('|').some(k=>!policyNormalize(k,result.policy)))throw Error('Đáp án rỗng sau chuẩn hóa tại câu '+n);const values=new Map();for(const x of result.policy.partial){const normalized=policyNormalize(x.answer,result.policy);if(!normalized)throw Error('Đáp án điểm một phần rỗng sau chuẩn hóa');if(key.split('|').some(k=>policyNormalize(k,result.policy)===normalized)||values.has(normalized)&&values.get(normalized)!==x.points)throw Error('Quy tắc điểm một phần mâu thuẫn tại câu '+n);values.set(normalized,x.points);}}
for(const k of ['objective','excludedErrors'])if(r[k])result[k]=String(r[k]).slice(0,4000);
return result;});}
function policyNormalize(s,p={}){let value=String(s??'').normalize('NFKC').trim().replace(/\s+/g,' ');if(p.ignorePunctuation)value=value.replace(/[\p{P}]/gu,'').trim().replace(/\s+/g,' ');return p.caseSensitive?value:value.toLowerCase();}
function grade(rows,answers,manual={}){rows=validateKey(rows);let score=0,max=0;const items=rows.map(q=>{max+=q.points;const answer=String(answers[q.number]??'').trim(),p=q.policy||{};let earned=null,reason='Giáo viên chấm theo barem';
if(q.type!=='written'){const matches=q.key.split('|').some(k=>policyNormalize(k,p)===policyNormalize(answer,p));const partial=(p.partial||[]).filter(x=>policyNormalize(x.answer,p)===policyNormalize(answer,p));if(matches){earned=q.points;reason='Khớp đáp án / biến thể đã duyệt';}else if(partial.length){if(new Set(partial.map(x=>x.points)).size>1)throw Error('Quy tắc điểm một phần mâu thuẫn tại câu '+q.number);earned=partial[0].points;reason='Khớp đáp án cho điểm một phần đã duyệt';}else{earned=p.reviewUnmatched&&answer?null:0;reason=earned===null?'Biến thể chưa được duyệt — cần giáo viên':'Không khớp đáp án đã duyệt';}}
if(Object.hasOwn(manual,q.number)&&manual[q.number]!==''&&manual[q.number]!==null){earned=Number(manual[q.number]);if(!Number.isFinite(earned)||earned<0||earned>q.points)throw Error('Điểm câu '+q.number+' phải từ 0 đến '+q.points);reason='Điểm do giáo viên quyết định';}
if(earned!==null)score+=earned;return {...q,answer,earned,reason};});return {items,score:Math.round(score*100)/100,max:Math.round(max*100)/100,complete:items.every(x=>x.earned!==null)};}
function csvCell(value){let s=String(value??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
const api={policyNormalize,normalize,parseAnswers,detectExamCode,validateKey,grade,csvCell};if(typeof module!=='undefined')module.exports=api;root.EFSCore=api;})(globalThis);
