(function(root){'use strict';
const encode=s=>new TextEncoder().encode(s);
const xml=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function crc(bytes){let value=0xffffffff;for(const byte of bytes){value^=byte;for(let i=0;i<8;i++)value=(value>>>1)^((value&1)?0xedb88320:0);}return (value^0xffffffff)>>>0;}
function zip(files){const pieces=[],directory=[];let offset=0;const header=(size)=>{const b=new Uint8Array(size);return [b,new DataView(b.buffer)];};for(const [name,text] of Object.entries(files)){const n=encode(name),data=encode(text),checksum=crc(data),[h,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,checksum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);pieces.push(h,n,data);const [c,d]=header(46);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,checksum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,n.length,true);d.setUint32(42,offset,true);directory.push(c,n);offset+=h.length+n.length+data.length;}
 const directorySize=directory.reduce((n,b)=>n+b.length,0),[end,v]=header(22);v.setUint32(0,0x06054b50,true);v.setUint16(8,Object.keys(files).length,true);v.setUint16(10,Object.keys(files).length,true);v.setUint32(12,directorySize,true);v.setUint32(16,offset,true);const result=new Uint8Array(offset+directorySize+22);let i=0;for(const b of [...pieces,...directory,end]){result.set(b,i);i+=b.length;}return result;}
function workbook(results){const rows=[['Mã HS','Mã đề','Bài kiểm tra','Điểm','Tối đa','Ngày duyệt','Phiên bản đáp án','Chi tiết'],...results.map(r=>[r.student,r.code,r.title,r.score,r.max,r.savedAt,r.keyRevision||0,r.items.map(q=>'Câu '+q.number+': '+q.answer+'; '+q.earned+'/'+q.points).join(' | ')])];const sheet=rows.map((row,i)=>'<row r="'+(i+1)+'">'+row.map((x,j)=>{const ref=String.fromCharCode(65+j)+(i+1);return typeof x==='number'&&Number.isFinite(x)?'<c r="'+ref+'"><v>'+x+'</v></c>':'<c r="'+ref+'" t="inlineStr"><is><t xml:space="preserve">'+xml(x)+'</t></is></c>';}).join('')+'</row>').join('');return zip({
 '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Điểm đã duyệt" sheetId="1" r:id="rId1"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
 'xl/worksheets/sheet1.xml':'<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+sheet+'</sheetData></worksheet>'});}
const api={workbook};if(typeof module==='object')module.exports=api;root.EFSExcel=api;
if(typeof document!=='undefined'){const button=document.getElementById('exportExcel');if(button)button.onclick=()=>{try{const data=JSON.parse(localStorage.getItem('efs_grading_v2'));if(!data?.results?.length)throw Error('Chưa có điểm để xuất.');const url=URL.createObjectURL(new Blob([workbook(data.results)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download='EFS_Grading.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){const status=document.getElementById('status');status.className='error';status.textContent=e.message;}};}
})(globalThis);
