'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {suggest,validateInput}=require('./ai-provider.cjs');
const assets=new Set(['index.html','style.css','core.js','workflow.js','app.js','batch.js','backup.js','ai-client.js','excel.js']);
function createServer(env=process.env,transport=fetch){const token=env.EFS_TEACHER_TOKEN||'',enabled=env.EFS_ALLOW_EXTERNAL_AI==='true'&&token.length>=32&&!!env.OPENAI_API_KEY&&!!env.EFS_AI_MODEL;let inflight=0,day='',attempts=0;const dailyLimit=Number(env.EFS_AI_DAILY_ATTEMPTS||50);if(!Number.isInteger(dailyLimit)||dailyLimit<1||dailyLimit>500)throw Error('Invalid daily attempt limit');const hits=new Map();
 return http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Cache-Control','no-store');const reply=(code,value)=>{res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};const pathname=new URL(req.url,'http://localhost').pathname;if(req.method==='GET'&&pathname==='/api/health'){reply(200,{aiEnabled:enabled,storage:'browser-local',mode:'single-teacher-pilot'});return;}
 if(pathname==='/api/grade'){if(req.method!=='POST'){reply(405,{error:'Method not allowed'});return;}if(!enabled){reply(503,{error:'AI disabled'});return;}const address=req.socket.remoteAddress;const local=['127.0.0.1','::1','::ffff:127.0.0.1'].includes(address);if(!local&&(!env.EFS_PUBLIC_ORIGIN?.startsWith('https://')||req.headers['x-forwarded-proto']!=='https')){reply(403,{error:'HTTPS required'});return;}
 const now=Date.now(),window=Math.floor(now/60000);const rate=hits.get(address)||{window,count:0};if(rate.window!==window){rate.window=window;rate.count=0;}rate.count++;hits.set(address,rate);if(hits.size>10000){hits.clear();hits.set(address,rate);}if(rate.count>10){reply(429,{error:'Rate limited'});return;}
 const provided=Buffer.from((req.headers.authorization||'').replace(/^Bearer /,'')),expected=Buffer.from(token);if(provided.length!==expected.length||!crypto.timingSafeEqual(provided,expected)){reply(401,{error:'Unauthorized'});return;}const origin=env.EFS_PUBLIC_ORIGIN||'http://'+req.headers.host;if(req.headers.origin!==origin){reply(403,{error:'Origin rejected'});return;}if(!/^application\/json(?:;|$)/i.test(req.headers['content-type']||'')){reply(415,{error:'JSON required'});return;}if(inflight>=2){reply(429,{error:'Busy'});return;}let bytes=0,chunks=[],tooLarge=false;try{for await(const chunk of req){bytes+=chunk.length;if(bytes>40000){tooLarge=true;break;}chunks.push(chunk);}if(tooLarge){reply(413,{error:'Request too large'});return;}const input=JSON.parse(Buffer.concat(chunks).toString('utf8'));validateInput(input);inflight++;try{const result=await suggest(input,{key:env.OPENAI_API_KEY,model:env.EFS_AI_MODEL},transport,()=>{const today=new Date().toISOString().slice(0,10);if(today!==day){day=today;attempts=0;}if(attempts>=dailyLimit)throw Error('Budget exhausted');attempts++;});reply(200,result);}finally{inflight--;}}catch{reply(422,{error:'No valid AI suggestion. Teacher review required.'});}return;}
 if(req.method==='GET'){const asset=pathname==='/'?'index.html':pathname.slice(1);if(assets.has(asset)){const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};res.writeHead(200,{'Content-Type':types[path.extname(asset)]});fs.createReadStream(path.join(__dirname,asset)).pipe(res);return;}}
 reply(404,{error:'Not found'});
 });}
if(require.main===module){const host=process.env.EFS_BIND_HOST||'127.0.0.1';if(host!=='127.0.0.1'&&!process.env.EFS_PUBLIC_ORIGIN?.startsWith('https://'))throw Error('Configure HTTPS public origin before remote binding');const server=createServer();server.requestTimeout=45000;server.headersTimeout=10000;server.listen(Number(process.env.PORT||3000),host,()=>console.log('EFS Grading single-teacher pilot listening'));}
module.exports={createServer};
