(function(root){'use strict';
const C=typeof module==='object'?require('./core.js'):root.EFSCore;
const copy=x=>JSON.parse(JSON.stringify(x));
const dangerous=k=>['__proto__','prototype','constructor'].includes(k);
function validateState(input){
 if(!input||typeof input!=='object'||Array.isArray(input)||!input.versions||Array.isArray(input.versions)||typeof input.versions!=='object'||!Array.isArray(input.results))throw Error('Cấu trúc dữ liệu không hợp lệ.');
 const s=copy(input);const codes=Object.keys(s.versions);if(codes.length>500||s.results.length>20000)throw Error('Dữ liệu vượt giới hạn.');
 if(new Set(codes.map(c=>c.toUpperCase())).size!==codes.length)throw Error('Mã đề trùng hoa/thường.');
 for(const [code,v] of Object.entries(s.versions)){if(dangerous(code)||!code.trim()||code.length>30||!v||typeof v.title!=='string'||!v.title.trim()||!Array.isArray(v.questions))throw Error('Mã đề / tên bài không hợp lệ.');v.questions=C.validateKey(v.questions);}
 for(const r of s.results){if(!r||typeof r.student!=='string'||!r.student.trim()||typeof r.code!=='string'||typeof r.title!=='string'||!Number.isFinite(r.score)||!Number.isFinite(r.max)||r.score<0||r.score>r.max||r.max<=0||!Array.isArray(r.items)||!Array.isArray(r.questions))throw Error('Kết quả đã lưu không hợp lệ.');C.validateKey(r.questions);if(r.items.length!==r.questions.length||r.items.some((x,i)=>!x||x.number!==r.questions[i].number||!Number.isFinite(x.earned)||x.earned<0||x.earned>r.questions[i].points))throw Error('Chi tiết kết quả không hợp lệ.');if(Math.abs(r.items.reduce((n,x)=>n+x.earned,0)-r.score)>0.011||Math.abs(r.questions.reduce((n,x)=>n+x.points,0)-r.max)>0.011)throw Error('Tổng điểm không khớp.');}
 if(s.queue!==undefined){if(!Array.isArray(s.queue)||s.queue.length>1000||s.queue.some(x=>!x||typeof x.id!=='string'||typeof x.text!=='string'||!['DRAFT','PROCESSING','NEEDS REVIEW','APPROVED','FAILED'].includes(x.status)))throw Error('Hàng đợi không hợp lệ.');const ids=new Set();for(const x of s.queue){if(ids.has(x.id)||!Array.isArray(x.pages)||!Array.isArray(x.issues)||typeof x.student!=='string'||typeof x.code!=='string'||x.pages.some(p=>!p||typeof p.name!=='string'||!Number.isInteger(p.number)||p.number<1))throw Error('Chi tiết hàng đợi không hợp lệ.');ids.add(x.id);if(x.keySnapshot){if(typeof x.keySnapshot.title!=='string')throw Error('Bản đáp án hàng đợi không hợp lệ.');C.validateKey(x.keySnapshot.questions);}if(x.candidate){validateState({versions:{},results:[x.candidate]});}}}
 if(s.keyHistory!==undefined){if(!Array.isArray(s.keyHistory)||s.keyHistory.length>5000)throw Error('Lịch sử mã đề không hợp lệ.');for(const v of s.keyHistory){if(!v||typeof v.code!=='string'||typeof v.title!=='string'||!Array.isArray(v.questions))throw Error('Lịch sử mã đề không hợp lệ.');C.validateKey(v.questions);}}
 if(s.audit!==undefined&&(!Array.isArray(s.audit)||s.audit.length>50000))throw Error('Nhật ký không hợp lệ.');return s;
}
function restore(storage,raw){if(raw.length>20*1024*1024)throw Error('Bản sao lưu tối đa 20 MB.');const p=JSON.parse(raw);if(p.format!=='efs-grading-backup'||p.schemaVersion!==1||p.storageKey!=='efs_grading_v2')throw Error('Định dạng / phiên bản sao lưu không hỗ trợ.');const next=validateState(p.data);for(const item of next.queue||[])if(item.status!=='APPROVED')delete item.candidate;const previous=storage.getItem('efs_grading_v2');if(previous!==null)storage.setItem('efs_grading_before_restore',previous);storage.setItem('efs_grading_v2',JSON.stringify(next));return next;}
function rollback(storage){const raw=storage.getItem('efs_grading_before_restore');if(!raw)throw Error('Chưa có bản trước khôi phục.');const next=validateState(JSON.parse(raw));const current=storage.getItem('efs_grading_v2');if(current!==null)storage.setItem('efs_grading_before_rollback',current);storage.setItem('efs_grading_v2',JSON.stringify(next));return next;}
function studentID(text){const normalized=String(text).normalize('NFKC').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d');const re=/^(?:ma[ \t]*(?:hoc[ \t]*sinh|hs)|student[ \t]*id)[ \t]*[:#=][ \t]*([^\s]+)[ \t]*$/gim;const ids=[...new Set([...normalized.matchAll(re)].map(x=>x[1]))];return {student:ids.length===1?ids[0]:null,status:ids.length>1?'conflict':ids.length?'matched':'missing'};}
function groupPages(pages,versions,idFactory){const output=[],groups=new Map();for(const page of pages){const identity=studentID(page.text),resolution=C.detectExamCode(page.text,Object.keys(versions));const code=resolution.status==='matched'?resolution.code:null;const key=identity.student&&code&&!page.error?JSON.stringify([identity.student,code]):null;let item=key&&groups.get(key);if(!item){item={id:idFactory(),student:identity.student||'',code:code||'',text:'',pages:[],status:page.error?'FAILED':'NEEDS REVIEW',issues:[],keySnapshot:code?copy(versions[code]):null};output.push(item);if(key)groups.set(key,item);}item.pages.push(page);item.text+=(item.text?'\n':'')+page.text;if(identity.status!=='matched')item.issues.push('Mã học sinh '+identity.status);if(!code)item.issues.push('Mã đề '+resolution.status);if(page.error)item.issues.push(page.error);if(page.warnings?.length)item.issues.push(...page.warnings);}
 for(const item of output){const parsed=C.parseAnswers(item.text);if(parsed.conflicts.length)item.issues.push('Câu trả lời mâu thuẫn: '+parsed.conflicts.join(', '));if(!Object.keys(parsed.answers).length)item.issues.push('Chưa có câu trả lời có số câu');item.issues=[...new Set(item.issues)];}return output;}
const api={validateState,restore,rollback,studentID,groupPages};if(typeof module==='object')module.exports=api;root.EFSWorkflow=api;
})(globalThis);
