const {JSDOM}=require('jsdom'),{indexedDB}=require('fake-indexeddb'),fs=require('node:fs'),a=require('node:assert/strict'),path=require('node:path');const base=path.resolve(__dirname,'..')+'/';
function boot(raw){const dom=new JSDOM(fs.readFileSync(base+'index.html','utf8'),{runScripts:'outside-only',url:'https://efs.test/'}),w=dom.window;w.structuredClone=structuredClone;w.indexedDB=indexedDB;w.confirm=()=>true;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};if(raw)w.localStorage.setItem('efs_grading_v2',raw);for(const file of ['core.js','workflow.js'])w.eval(fs.readFileSync(base+file,'utf8'));w.eval(['app.js','ai-client.js','batch.js'].map(file=>fs.readFileSync(base+file,'utf8')).join('\n'));return {dom,w,$:id=>w.document.getElementById(id),state:()=>JSON.parse(w.localStorage.getItem('efs_grading_v2'))};}
(async()=>{const ctx=boot(),{w,$}=ctx;$('title').value='Unit';$('code').value='001';$('keyText').value='1 A\n2 B';$('buildKey').click();$('saveKey').click();$('batchMode').checked=true;const files=[new File(['Mã HS: HS1\nMã đề: 001\n1 A'],'HS1-p1.txt',{type:'text/plain'}),new File(['bad'],'bad.bin',{type:'application/octet-stream'}),new File(['Mã HS: HS1\nMã đề: 001\n2 B'],'HS1-p2.txt',{type:'text/plain'}),new File(['Mã HS: HS2\nMã đề: 001\n1 A\n2 B'],'HS2.txt',{type:'text/plain'}),new File(['1 A'],'orphan.txt',{type:'text/plain'})];Object.defineProperty($('files'),'files',{value:files,configurable:true});await $('readBatch').onclick();const queue=ctx.state().queue;a.equal(queue.length,4);a.equal(queue[0].pages.length,2);a.equal(queue[1].status,'FAILED');a.equal(queue[2].student,'HS2');a.equal(queue[3].student,'');a.equal(ctx.state().results.length,0);
// Key edited after reading must not alter the snapshot used for this batch.
$('keyRows').querySelector('.qkey').value='C';$('saveKey').click();a.equal(ctx.state().versions['001'].revision,2);a.equal(ctx.state().keyHistory.length,1);
$('queue').querySelectorAll('button')[0].click();$('checked').checked=true;$('toReview').click();a.match($('score').textContent,/10.00/,$('status').textContent);$('approved').checked=true;$('stageBatch').click();a.equal(ctx.state().queue[0].candidate.keyRevision,1);a.equal(ctx.state().results.length,0);$('approveBatch').click();a.equal(ctx.state().results.length,1);a.equal(ctx.state().queue[0].status,'APPROVED');$('approveBatch').click();a.equal(ctx.state().results.length,1);$('queue').querySelectorAll('button')[0].click();a.match($('status').textContent,/khóa/);
// A checked bulk candidate cannot remain eligible once reopened for changes.
$('queue').querySelectorAll('button')[2].click();$('checked').checked=true;$('toReview').click();$('approved').checked=true;$('stageBatch').click();a.ok(ctx.state().queue[2].candidate);$('queue').querySelectorAll('button')[2].click();a.equal(ctx.state().queue[2].candidate,null);$('approveBatch').click();a.equal(ctx.state().results.length,1);
const raw=w.localStorage.getItem('efs_grading_v2'),reloaded=boot(raw);a.equal(reloaded.state().queue.length,4);a.equal(reloaded.state().results.length,1);a.equal(reloaded.state().queue[0].keySnapshot.revision,1);a.equal(reloaded.$('queue').children.length,4);reloaded.w.close();w.close();console.log('PASS batch: real TXT reader, explicit grouping, isolated file error, pinned key revision, staged/bulk approval, lock, stale-candidate rejection and reload');})().catch(e=>{console.error(e);process.exitCode=1;});
