const {test}=require('node:test'),a=require('node:assert/strict');
const C=require('../core.js'),W=require('../workflow.js');
const question={number:1,type:'short',key:'He walks',points:2};
const versions={'001':{title:'Unit 1',questions:[question],revision:1}};
test('target policies keep missing s pending, explicit variant/partial and punctuation rules',()=>{const q={...question,policy:{reviewUnmatched:true}};a.equal(C.grade([q],{1:'He walk'}).complete,false);a.equal(C.grade([q],{1:'He walks'}).score,2);a.equal(C.grade([{...q,key:'He walks | He walk'}],{1:'He walk'}).score,2);a.equal(C.grade([{...q,policy:{partial:[{answer:'He walk',points:1}]}}],{1:'He walk'}).score,1);a.equal(C.grade([question],{1:'He walks.'}).score,0);a.equal(C.grade([{...question,policy:{ignorePunctuation:true}}],{1:'He walks.'}).score,2);a.equal(C.grade([{...question,policy:{caseSensitive:true}}],{1:'he walks'}).score,0);a.equal(C.grade([q],{1:'He walk'},{1:1}).score,1);a.throws(()=>C.validateKey([{...question,policy:{partial:[{answer:'x',points:9}]}}]));});
test('pages only join on explicit student and exact known code; unknown/conflict stay separate',()=>{let n=0;const pages=[{text:'Mã HS: HS1\nMã đề: 001\n1 He walks',name:'one',number:1},{text:'Student ID: HS1\nExam code: 001\n2 B',name:'two',number:2},{text:'1 A',name:'orphan',number:1},{text:'Mã HS: HS2\nMã đề: 999\n1 B',name:'unknown',number:1},{text:'Mã HS: HS3\nMã đề: 001\nMã đề: 999\n1 C',name:'mixed',number:1},{text:'',name:'bad',number:1,error:'Failed OCR'}];const items=W.groupPages(pages,versions,()=>String(++n));a.equal(items.length,5);a.equal(items[0].pages.length,2);a.equal(items[0].code,'001');a.equal(items[0].keySnapshot.revision,1);a.equal(items[1].student,'');a.equal(items[2].code,'');a.equal(items[3].code,'');a.equal(items[4].status,'FAILED');versions['001'].questions[0].key='B';a.equal(items[0].keySnapshot.questions[0].key,'He walks');versions['001'].questions[0].key='He walks';});
test('restore validates before writes and retains current state; clears unapproved bulk candidates',()=>{const old={versions,results:[]};const data=new Map([['efs_grading_v2',JSON.stringify(old)]]);const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};const backup=s=>JSON.stringify({format:'efs-grading-backup',schemaVersion:1,storageKey:'efs_grading_v2',data:s});a.throws(()=>W.restore(storage,backup({versions:{bad:{title:'x',questions:[]}},results:[]})));a.equal(data.get('efs_grading_v2'),JSON.stringify(old));const next=W.restore(storage,backup(old));a.deepEqual(next,old);a.equal(data.get('efs_grading_before_restore'),JSON.stringify(old));a.throws(()=>W.restore(storage,JSON.stringify({format:'efs-grading-backup',schemaVersion:9,data:old})));const failStorage={...storage,setItem:()=>{throw Error('Quota');}};a.throws(()=>W.restore(failStorage,backup(old)));a.deepEqual(JSON.parse(data.get('efs_grading_v2')),old);});
test('malformed approved totals/prototype keys and queue metadata cannot enter restored data',()=>{const result={student:'HS',code:'001',title:'X',questions:[question],items:[{number:1,earned:2}],score:1,max:2};a.throws(()=>W.validateState({versions,results:[result]}));a.throws(()=>W.validateState(JSON.parse('{"versions":{"__proto__":{"title":"x","questions":[]}},"results":[]}')));a.throws(()=>W.validateState({versions,results:[],queue:[{id:'1',status:'NEEDS REVIEW',text:'x'}]}));});

test('leading-zero exam headers never become question 1 or consume next-line answers',()=>{const parsed=C.parseAnswers('Mã HS: 001\nMã đề: 001\n1 A\nMã HS: 001\nMã đề: 001\n2 B');a.deepEqual(parsed,{answers:{1:'A',2:'B'},conflicts:[]});a.deepEqual(C.parseAnswers('Mã đề: 101\n1 A').answers,{1:'A'});});

test('multi-line free responses retain continuation text for rubric review',()=>{a.deepEqual(C.parseAnswers('1 I went home.\nThen I cooked dinner.\n2 B').answers,{1:'I went home.\nThen I cooked dinner.',2:'B'});});

test('rollback preserves restored data in a checkpoint before returning to previous state',()=>{const previous={versions,results:[]},current={versions:{},results:[]};const data=new Map([['efs_grading_v2',JSON.stringify(current)],['efs_grading_before_restore',JSON.stringify(previous)]]);W.rollback({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});a.deepEqual(JSON.parse(data.get('efs_grading_v2')),previous);a.deepEqual(JSON.parse(data.get('efs_grading_before_rollback')),current);});
